add_newline = false
command_timeout = 1000
scan_timeout = 30
palette = "tokyonight_storm"
format = "$directory$git_branch$git_status$python$dotnet$bun$nodejs$docker_context$kubernetes$fill$cmd_duration$line_break$character"
right_format = "$time"

[fill]
symbol = " "

[directory]
truncation_length = 4
truncate_to_repo = true
style = "bold sky"
read_only = " 󰌾"
read_only_style = "red"

[git_branch]
symbol = ""
style = "lavender"

[git_status]
style = "amber"
format = '([\[$all_status$ahead_behind\]]($style) )'
ahead = "⇡${count}"
behind = "⇢${count}"
diverged = "⇕⇡${ahead_count}⇢${behind_count}"
modified = "~${count}"
staged = "+${count}"
untracked = "?${count}"
stashed = "*${count}"

[python]
symbol = " "
format = "via [$symbol($version )]($style)"
style = "amber"

[dotnet]
symbol = "󰪮 "
format = "via [$symbol($version )]($style)"
style = "sky"

[bun]
symbol = " "
format = "via [$symbol($version )]($style)"
style = "peach"

[nodejs]
symbol = " "
format = "via [$symbol($version )]($style)"
style = "emerald"

[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "teal"
only_with_files = true

[kubernetes]
symbol = "⎈ "
format = "on [$symbol$context( ($namespace))]($style) "
style = "teal"
disabled = false

[cmd_duration]
min_time = 500
format = "took [$duration]($style) "
style = "muted"

[time]
disabled = false
format = "[$time]($style)"
style = "muted"
time_format = "%H:%M"

[character]
success_symbol = "[❯](emerald)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](lavender)"

[palettes.tokyonight_storm]
sky = "#7aa2f7"
lavender = "#bb9af7"
emerald = "#9ece6a"
amber = "#e0af68"
peach = "#ff9e64"
teal = "#7dcfff"
muted = "#9aa5ce"
red = "#f7768e"
