# shellcheck shell=bash
export DOTFILES_DEVELOPER_ROOT="${DOTFILES_DEVELOPER_ROOT:-$HOME/Developer}"
export DOTFILES_HOMEBREW_PREFIX="${DOTFILES_HOMEBREW_PREFIX:-/opt/homebrew}"
export DOTFILES_LMSTUDIO_HOME="${DOTFILES_LMSTUDIO_HOME:-$HOME/.lmstudio}"
export DOTFILES_EDITOR="${DOTFILES_EDITOR:-nvim}"
export DOTFILES_OBSIDIAN_REPO_PATH="${DOTFILES_OBSIDIAN_REPO_PATH:-$DOTFILES_DEVELOPER_ROOT/personal/projects/obsidian-store}"
export DOTFILES_DOTNET_VERSION="${DOTFILES_DOTNET_VERSION:-8}"
export DOTFILES_SCREENSHOTS_PATH="${DOTFILES_SCREENSHOTS_PATH:-$HOME/Desktop/Screenshots}"

export EDITOR="$DOTFILES_EDITOR"
export VISUAL="$DOTFILES_EDITOR"
export LANG="en_US.UTF-8"
export BUN_INSTALL="$HOME/.bun"

# Homebrew
export HOMEBREW_NO_ENV_HINTS=1
